### ISSUE TITLE
Error: Failed to get devices

### ISSUE THREAD

**Issue by ayghazali** [judge/homebridge-hikconnect#1]
First of all, thank you for creating this plugin!  
I'm having an issue where it says:  
Error: Failed to get devices
    at HikConnectClient.getDevices (/usr/local/lib/node_modules/homebridge-hikconnect/src/client/index.js:65:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HikConnectPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-hikconnect/src/index.js:28:23)

**Comment by scorpioRED** [comment]
Hi!
In my Hikvision account, I have shared with me cameras, and it’s working on the ios Hik-Connect app.
I didn’t get any errors, however, I don't see any cameras or new accessories in my homekit app.
Hrere is result from page https://api.hik-connect.com/v3/userdevices/v1/devices/pagelist?groupId=-1&limit=100&offset=0&filter=TIME_PLAN,CONNECTION,SWITCH,STATUS,STATUS_EXT,WIFI,NODISTURB,P2P,KMS,HIDDN


{"connectionInfos":{"245561706":{"localIp":"192.168.1.31","netIp":"31.43.78.186","localRtspPort":0,"netRtspPort":0,"localCmdPort":9010,"netCmdPort":9010,"localStreamPort":9020,"netHttpPort":0,"localHttpPort":0,"netStreamPort":9020,"netType":3,"wanIp":null,"upnp":false}},"cameraInfos":[],"p2pInfos":{"245561706":[{"ip":"34.255.247.207","port":6000},{"ip":"34.252.202.35","port":6000}]},"alarmNodisturbInfos":{},"kmsInfos":{"245561706":{"secretKey":"25a305ce7e07909b4237d935e19ab495b40d5550f8364ff78ba57fb983195a4d","version":"101"}},"timePlanInfos":{"245561706":[{"deviceSerial":"245561706","channelNo":0,"type":0,"enable":0,"weekPlans":[{"weekDay":"0,1,2,3,4,5,6","timePlan":[]}]},{"deviceSerial":"245561706","channelNo":0,"type":2,"enable":0,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"245561706","channelNo":0,"type":4,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[{"startTime":"-1:65","endTime":"-1:65"}]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"245561706","channelNo":0,"type":5,"enable":0,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"245561706","channelNo":0,"type":7,"enable":0,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]}]},"statusExtInfos":{"245561706":{"upgradeAvailable":0}},"meta":{"code":200,"message":"操作成功","moreInfo":{}},"page":{"offset":0,"limit":100,"totalResults":0,"hasNext":false},"statusInfos":{"245561706":{"diskNum":2,"diskState":"00--------------","globalStatus":1,"pirStatus":0,"isEncrypt":1,"encryptPwd":"166e5d9239341a4fb850a60a8c7daaab","upgradeAvailable":0,"upgradeProcess":0,"upgradeStatus":2,"alarmSoundMode":0,"optionals":{"latestUnbandTime":"1615021683307","BodyDetectTimeInterval":"0","updateCode":"0","Remind_Way":"-1","display_mode":"{  \"mode\": 1 }","Record_Mode":"{  \"mode\": 20867244 }","wanIp":"31.43.78.186","CustomVoice":"[]","Route_LinkageStatus":"0","Battery_WorkStatus":"{\"KeepAlive\":0,\"WorkTime\":0}","daylightSavingTime":"0","Alarm_DetectHumanCar":"{\"type\":0}","tzCode":"0","OSD":"[{\"name\":\"01 - 13П - Пiдстанцiя\",\"channel\":\"1\"},{\"name\":\"02 - 13П - Паркiнг\",\"channel\":\"2\"},{\"name\":\"03 - 6П - Лiва\",\"channel\":\"3\"},{\"name\":\"04 - 6П - Права\",\"channel\":\"4\"},{\"name\":\"05 - 1П - Парковка\",\"channel\":\"5\"},{\"name\":\"06 - 1П - Смiтники\",\"channel\":\"6\"},{\"name\":\"07 - 1П - Зовнiшня\",\"channel\":\"7\"},{\"name\":\"08 - 2П - Зовнiшня\",\"channel\":\"8\"},{\"name\":\"09 - 3П - Зовнiшня\",\"channel\":\"9\"},{\"name\":\"10 - 4П - Зовнiшня\",\"channel\":\"10\"},{\"name\":\"11 - 5П - Хол\",\"channel\":\"11\"},{\"name\":\"12 - 6П - Хол\",\"channel\":\"12\"},{\"name\":\"13 - 7П - Зовнiшня\",\"channel\":\"13\"},{\"name\":\"14 - 8П - Зовнiшня\",\"channel\":\"14\"},{\"name\":\"15 - 9П - Зовнiшня\",\"channel\":\"15\"},{\"name\":\"16 - 10П - Зовнiшня\",\"channel\":\"16\"},{\"name\":\"17 - 11П - Зовнiшня\",\"channel\":\"17\"},{\"name\":\"18 - 12П - Зовнiшня\",\"channel\":\"18\"},{\"name\":\"19 - 13П - Зовнiшня\",\"channel\":\"19\"},{\"name\":\"20 - 1П - Хол\",\"channel\":\"20\"},{\"name\":\"21 - 2П - Хол\",\"channel\":\"21\"},{\"name\":\"22 - 3П - Хол\",\"channel\":\"22\"},{\"name\":\"23 - 4П - Хол\",\"channel\":\"23\"},{\"name\":\"24 - 5П - Лiфт\",\"channel\":\"24\"},{\"name\":\"25 - 6П - Лiфт\",\"channel\":\"25\"},{\"name\":\"26 - 7П - Хол\",\"channel\":\"26\"},{\"name\":\"27 - 8П - Хол\",\"channel\":\"27\"},{\"name\":\"28 - 9П - Хол\",\"channel\":\"28\"},{\"name\":\"29 - 10П - Хол\",\"channel\":\"29\"},{\"name\":\"30 - 11П - Хол\",\"channel\":\"30\"},{\"name\":\"31 - 12П - Хол\",\"channel\":\"31\"},{\"name\":\"32 - 13П - Хол\",\"channel\":\"32\"}]","CustomVoice_Volume":"{\"volume\":0}","diskHealth":"0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1","inverse_mode":"{  \"mode\": 0,  \"enable\": 0,  \"position\": 1 }","OnlineStatus":"1","timeZone":"UTC","Alarm_Light":"{\"luminance\":0}","ROI":"{  \"xCoord\": \"-1.00\",  \"yCoord\": \"-1.00\",  \"width\": \"-1.00\",  \"height\": \"-1.00\" }","diskCapacity":"1907729,5723166,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1","Alarm_Interval":"-1","Temperature_Threshold":"-1","kms_version":"100","NightVision_Model":"{  \"graphicType\": -1,  \"luminance\": -1 }","timeFormat":"0","talkMode":"{  \"mode\": 1 }","ICR":"0","superState":"0","voiceIndex":"0","latestUnbindTime":"1615021683307","lastUpgradeTime":"1623148016369"}}},"wifiInfos":{"245561706":{"netName":"eth0","netType":"wire","address":"192.168.1.31","mask":"255.255.255.0","gateway":"192.168.1.1","signal":100,"ssid":null}},"switchStatusInfos":{"245561706":[{"deviceSerial":"245561706","channelNo":0,"type":2,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":7,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":10,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":15,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":22,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":29,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":37,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":200,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":202,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":300,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":301,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":302,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":303,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":304,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":305,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":602,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":603,"enable":false},{"deviceSerial":"245561706","channelNo":0,"type":700,"enable":false}]},"deviceInfos":[{"name":"OSBB-analog32","deviceSerial":"245561706","fullSerial":"DVR/DVS-72-A3220200924CCWR245561706WCVU","deviceType":"DVR/DVS-72-A","devicePicPrefix":"https://devpic.ezvizlife.com/device/image/DVR-DVS-72-A/","version":"V4.25.000 build 200925","supportExt":"{\"68\":\"1\",\"26\":\"4\",\"49\":\"1\",\"29\":\"1\",\"171\":\"8\",\"292\":\"1\",\"175\":\"1\",\"154\":\"1\",\"232\":\"0\",\"233\":\"0\",\"354\":\"0\",\"234\":72,\"257\":\"1\",\"30\":\"1\",\"31\":\"1\",\"11\":\"0\",\"33\":\"1\",\"99\":\"1\",\"34\":\"1\",\"13\":\"0\",\"14\":\"1\",\"59\":\"1\",\"17\":\"1\",\"260\":\"1\",\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"149\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"1\"}","status":1,"userDeviceCreateTime":"2021-03-06 09:10:06","casIp":"eucas.ezvizlife.com","casPort":6500,"channelNumber":72,"hik":true,"deviceCategory":"COMMON","deviceSubCategory":"UNKNOWN","ezDeviceCapability":"{\"262\":\"1\",\"175\":\"1\",\"263\":\"0\",\"264\":\"1\",\"232\":\"0\",\"265\":\"1\",\"233\":\"0\",\"266\":\"0\",\"234\":1,\"267\":\"1\",\"289\":\"1\",\"30\":\"0\",\"31\":\"0\"}","customType":"DS-7232HQHI-K2","offlineTime":"2022-04-21 18:27:57","offlineNotify":0,"accessPlatform":true,"deviceDomain":"245561706","instructionBook":"http://devpic.ezvizlife.com/device/image/DVR/DVS-72-A/instruction.jpeg","deviceShareInfo":{"isShared":2,"permission":3,"inviterName":"rdovbeta"},"feature":null,"riskLevel":0,"offlineTimestamp":1650565677000}]}

**Comment by judge** [comment]
Could you please check this JSON again? It is invalid, maybe Github did some formatting on his own. Can you maybe upload the raw json output to some file hosting?

**Comment by scorpioRED** [comment]
Sure
`{
  "connectionInfos": {
    "245561706": {
      "localIp": "192.168.1.31",
      "netIp": "31.43.78.186",
      "localRtspPort": 0,
      "netRtspPort": 0,
      "localCmdPort": 9010,
      "netCmdPort": 9010,
      "localStreamPort": 9020,
      "netHttpPort": 0,
      "localHttpPort": 0,
      "netStreamPort": 9020,
      "netType": 3,
      "wanIp": null,
      "upnp": false
    }
  },
  "cameraInfos": [],
  "p2pInfos": {
    "245561706": [
      {
        "ip": "34.255.247.207",
        "port": 6000
      },
      {
        "ip": "34.252.202.35",
        "port": 6000
      }
    ]
  },
  "alarmNodisturbInfos": {},
  "kmsInfos": {
    "245561706": {
      "secretKey": "25a305ce7e07909b4237d935e19ab495b40d5550f8364ff78ba57fb983195a4d",
      "version": "101"
    }
  },
  "timePlanInfos": {
    "245561706": [
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 0,
        "enable": 0,
        "weekPlans": [
          {
            "weekDay": "0,1,2,3,4,5,6",
            "timePlan": []
          }
        ]
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 2,
        "enable": 0,
        "weekPlans": [
          {
            "weekDay": "0",
            "timePlan": []
          },
          {
            "weekDay": "1",
            "timePlan": []
          },
          {
            "weekDay": "2",
            "timePlan": []
          },
          {
            "weekDay": "3",
            "timePlan": []
          },
          {
            "weekDay": "4",
            "timePlan": []
          },
          {
            "weekDay": "5",
            "timePlan": []
          },
          {
            "weekDay": "6",
            "timePlan": []
          }
        ]
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 4,
        "enable": -1,
        "weekPlans": [
          {
            "weekDay": "0",
            "timePlan": [
              {
                "startTime": "-1:65",
                "endTime": "-1:65"
              }
            ]
          },
          {
            "weekDay": "1",
            "timePlan": []
          },
          {
            "weekDay": "2",
            "timePlan": []
          },
          {
            "weekDay": "3",
            "timePlan": []
          },
          {
            "weekDay": "4",
            "timePlan": []
          },
          {
            "weekDay": "5",
            "timePlan": []
          },
          {
            "weekDay": "6",
            "timePlan": []
          }
        ]
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 5,
        "enable": 0,
        "weekPlans": [
          {
            "weekDay": "0",
            "timePlan": []
          },
          {
            "weekDay": "1",
            "timePlan": []
          },
          {
            "weekDay": "2",
            "timePlan": []
          },
          {
            "weekDay": "3",
            "timePlan": []
          },
          {
            "weekDay": "4",
            "timePlan": []
          },
          {
            "weekDay": "5",
            "timePlan": []
          },
          {
            "weekDay": "6",
            "timePlan": []
          }
        ]
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 7,
        "enable": 0,
        "weekPlans": [
          {
            "weekDay": "0",
            "timePlan": []
          },
          {
            "weekDay": "1",
            "timePlan": []
          },
          {
            "weekDay": "2",
            "timePlan": []
          },
          {
            "weekDay": "3",
            "timePlan": []
          },
          {
            "weekDay": "4",
            "timePlan": []
          },
          {
            "weekDay": "5",
            "timePlan": []
          },
          {
            "weekDay": "6",
            "timePlan": []
          }
        ]
      }
    ]
  },
  "statusExtInfos": {
    "245561706": {
      "upgradeAvailable": 0
    }
  },
  "meta": {
    "code": 200,
    "message": "操作成功",
    "moreInfo": {}
  },
  "page": {
    "offset": 0,
    "limit": 100,
    "totalResults": 0,
    "hasNext": false
  },
  "statusInfos": {
    "245561706": {
      "diskNum": 2,
      "diskState": "00--------------",
      "globalStatus": 1,
      "pirStatus": 0,
      "isEncrypt": 1,
      "encryptPwd": "166e5d9239341a4fb850a60a8c7daaab",
      "upgradeAvailable": 0,
      "upgradeProcess": 0,
      "upgradeStatus": 2,
      "alarmSoundMode": 0,
      "optionals": {
        "latestUnbandTime": "1615021683307",
        "BodyDetectTimeInterval": "0",
        "updateCode": "0",
        "Remind_Way": "-1",
        "display_mode": "{  \"mode\": 1 }",
        "Record_Mode": "{  \"mode\": 20867244 }",
        "wanIp": "31.43.78.186",
        "CustomVoice": "[]",
        "Route_LinkageStatus": "0",
        "Battery_WorkStatus": "{\"KeepAlive\":0,\"WorkTime\":0}",
        "daylightSavingTime": "0",
        "Alarm_DetectHumanCar": "{\"type\":0}",
        "tzCode": "0",
        "OSD": "[{\"name\":\"01 - 13П - Пiдстанцiя\",\"channel\":\"1\"},{\"name\":\"02 - 13П - Паркiнг\",\"channel\":\"2\"},{\"name\":\"03 - 6П - Лiва\",\"channel\":\"3\"},{\"name\":\"04 - 6П - Права\",\"channel\":\"4\"},{\"name\":\"05 - 1П - Парковка\",\"channel\":\"5\"},{\"name\":\"06 - 1П - Смiтники\",\"channel\":\"6\"},{\"name\":\"07 - 1П - Зовнiшня\",\"channel\":\"7\"},{\"name\":\"08 - 2П - Зовнiшня\",\"channel\":\"8\"},{\"name\":\"09 - 3П - Зовнiшня\",\"channel\":\"9\"},{\"name\":\"10 - 4П - Зовнiшня\",\"channel\":\"10\"},{\"name\":\"11 - 5П - Хол\",\"channel\":\"11\"},{\"name\":\"12 - 6П - Хол\",\"channel\":\"12\"},{\"name\":\"13 - 7П - Зовнiшня\",\"channel\":\"13\"},{\"name\":\"14 - 8П - Зовнiшня\",\"channel\":\"14\"},{\"name\":\"15 - 9П - Зовнiшня\",\"channel\":\"15\"},{\"name\":\"16 - 10П - Зовнiшня\",\"channel\":\"16\"},{\"name\":\"17 - 11П - Зовнiшня\",\"channel\":\"17\"},{\"name\":\"18 - 12П - Зовнiшня\",\"channel\":\"18\"},{\"name\":\"19 - 13П - Зовнiшня\",\"channel\":\"19\"},{\"name\":\"20 - 1П - Хол\",\"channel\":\"20\"},{\"name\":\"21 - 2П - Хол\",\"channel\":\"21\"},{\"name\":\"22 - 3П - Хол\",\"channel\":\"22\"},{\"name\":\"23 - 4П - Хол\",\"channel\":\"23\"},{\"name\":\"24 - 5П - Лiфт\",\"channel\":\"24\"},{\"name\":\"25 - 6П - Лiфт\",\"channel\":\"25\"},{\"name\":\"26 - 7П - Хол\",\"channel\":\"26\"},{\"name\":\"27 - 8П - Хол\",\"channel\":\"27\"},{\"name\":\"28 - 9П - Хол\",\"channel\":\"28\"},{\"name\":\"29 - 10П - Хол\",\"channel\":\"29\"},{\"name\":\"30 - 11П - Хол\",\"channel\":\"30\"},{\"name\":\"31 - 12П - Хол\",\"channel\":\"31\"},{\"name\":\"32 - 13П - Хол\",\"channel\":\"32\"}]",
        "CustomVoice_Volume": "{\"volume\":0}",
        "diskHealth": "0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1",
        "inverse_mode": "{  \"mode\": 0,  \"enable\": 0,  \"position\": 1 }",
        "OnlineStatus": "1",
        "timeZone": "UTC",
        "Alarm_Light": "{\"luminance\":0}",
        "ROI": "{  \"xCoord\": \"-1.00\",  \"yCoord\": \"-1.00\",  \"width\": \"-1.00\",  \"height\": \"-1.00\" }",
        "diskCapacity": "1907729,5723166,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1",
        "Alarm_Interval": "-1",
        "Temperature_Threshold": "-1",
        "kms_version": "100",
        "NightVision_Model": "{  \"graphicType\": -1,  \"luminance\": -1 }",
        "timeFormat": "0",
        "talkMode": "{  \"mode\": 1 }",
        "ICR": "0",
        "superState": "0",
        "voiceIndex": "0",
        "latestUnbindTime": "1615021683307",
        "lastUpgradeTime": "1623148016369"
      }
    }
  },
  "wifiInfos": {
    "245561706": {
      "netName": "eth0",
      "netType": "wire",
      "address": "192.168.1.31",
      "mask": "255.255.255.0",
      "gateway": "192.168.1.1",
      "signal": 100,
      "ssid": null
    }
  },
  "switchStatusInfos": {
    "245561706": [
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 2,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 7,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 10,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 15,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 22,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 29,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 37,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 200,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 202,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 300,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 301,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 302,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 303,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 304,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 305,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 602,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 603,
        "enable": false
      },
      {
        "deviceSerial": "245561706",
        "channelNo": 0,
        "type": 700,
        "enable": false
      }
    ]
  },
  "deviceInfos": [
    {
      "name": "OSBB-analog32",
      "deviceSerial": "245561706",
      "fullSerial": "DVR/DVS-72-A3220200924CCWR245561706WCVU",
      "deviceType": "DVR/DVS-72-A",
      "devicePicPrefix": "https://devpic.ezvizlife.com/device/image/DVR-DVS-72-A/",
      "version": "V4.25.000 build 200925",
      "supportExt": "{\"68\":\"1\",\"26\":\"4\",\"49\":\"1\",\"29\":\"1\",\"171\":\"8\",\"292\":\"1\",\"175\":\"1\",\"154\":\"1\",\"232\":\"0\",\"233\":\"0\",\"354\":\"0\",\"234\":72,\"257\":\"1\",\"30\":\"1\",\"31\":\"1\",\"11\":\"0\",\"33\":\"1\",\"99\":\"1\",\"34\":\"1\",\"13\":\"0\",\"14\":\"1\",\"59\":\"1\",\"17\":\"1\",\"260\":\"1\",\"1\":\"1\",\"2\":\"1\",\"3\":\"1\",\"4\":\"1\",\"5\":\"0\",\"6\":\"0\",\"149\":\"1\",\"7\":\"0\",\"8\":\"0\",\"9\":\"1\"}",
      "status": 1,
      "userDeviceCreateTime": "2021-03-06 09:10:06",
      "casIp": "eucas.ezvizlife.com",
      "casPort": 6500,
      "channelNumber": 72,
      "hik": true,
      "deviceCategory": "COMMON",
      "deviceSubCategory": "UNKNOWN",
      "ezDeviceCapability": "{\"262\":\"1\",\"175\":\"1\",\"263\":\"0\",\"264\":\"1\",\"232\":\"0\",\"265\":\"1\",\"233\":\"0\",\"266\":\"0\",\"234\":1,\"267\":\"1\",\"289\":\"1\",\"30\":\"0\",\"31\":\"0\"}",
      "customType": "DS-7232HQHI-K2",
      "offlineTime": "2022-04-21 18:27:57",
      "offlineNotify": 0,
      "accessPlatform": true,
      "deviceDomain": "245561706",
      "instructionBook": "http://devpic.ezvizlife.com/device/image/DVR/DVS-72-A/instruction.jpeg",
      "deviceShareInfo": {
        "isShared": 2,
        "permission": 3,
        "inviterName": "rdovbeta"
      },
      "feature": null,
      "riskLevel": 0,
      "offlineTimestamp": 1650565677000
    }
  ]
}`

Or here is JSON file on G-Drive
https://drive.google.com/file/d/1ZM9fK_CexZrV5STam6RpqeOLDb0pnk2-/view?usp=sharing

**Comment by judge** [comment]
Thanks! I just checked the response and it seems your device does not have locks or at least it does not expose it.
This plugin cannot show cameras currently, only locks for now.
