### ISSUE TITLE
Not added to the Home App

### ISSUE THREAD

**Issue by melnikovRV** [judge/homebridge-hikconnect#10]
I can see the door lock in Homebridge (and it works if I click on it), but it is not added to the Home App. I have already removed the bridge from the Home App and reinstalled the plugin.. I don't see it in the Home App
<img width="396" alt="Снимок экрана 2022-07-02 в 18 05 42" src="https://user-images.githubusercontent.com/45739282/177006503-072b75e8-93d7-4d4b-b674-6c53c2d9c6c1.png">

**Comment by judge** [comment]
I have no idea why it's not working in the Home app but I don't think it's the plugin's fault. Did you check all rooms in the Home app? Maybe it was added to a new room.
