### ISSUE TITLE
DS-KB8113-IME1

### ISSUE THREAD

**Issue by mbgdnv** [judge/homebridge-hikconnect#13]
Hi!
Can you add support of Hikvision DS-KB8113-IME1 doorbell? It has door lock functionality. Please see debug.

{"connectionInfos":{"J18155657":{"localIp":"10.0.1.85","netIp":"185.169.101.85","localRtspPort":0,"netRtspPort":0,"localCmdPort":9010,"netCmdPort":0,"localStreamPort":9020,"netHttpPort":0,"localHttpPort":0,"netStreamPort":0,"netType":3,"wanIp":"185.169.101.85","upnp":false}},"cameraInfos":[{"cameraId":"5f3dc009914f457c8bf6a0951b995f8f","cameraName":"Main Door Station","channelNo":1,"cameraCover":"https://irus.ezvizru.com/assets/imgs/public/homeDevice.jpeg","deviceSerial":"J18155657","isShow":1,"videoLevel":0,"videoQualityInfos":[{"streamType":2,"videoLevel":0},{"streamType":1,"videoLevel":2}],"streamBizUrl":"biz=1","vtmInfo":{"domain":"vtmrushw.ezvizru.com","externalIp":"vtmrushw.ezvizru.com","internalIp":null,"port":10554,"forceStreamType":0,"isBackup":0},"deviceChannelInfo":{"channelDeviceSerial":null,"channelNo":1,"privacyStatus":0,"powerStatus":0,"globalStatus":0,"signalStatus":1},"cameraShareInfo":{"isShared":1,"permission":-1,"inviterName":"jzmola"}}],"p2pInfos":{"J18155657":[{"ip":"162.62.18.46","port":6000}]},"alarmNodisturbInfos":{"J18155657":{"alarmEnable":0,"callingEnable":0}},"kmsInfos":{"J18155657":{"secretKey":"2af7653315ad7ecdebfe2217266a9d0f369e5c324c77a8a34c14c6a50aec7afd","version":"101"}},"timePlanInfos":{"J18155657":[{"deviceSerial":"J18155657","channelNo":0,"type":2,"enable":0,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"J18155657","channelNo":0,"type":4,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[{"startTime":"-1:65","endTime":"-1:65"}]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"J18155657","channelNo":0,"type":5,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"J18155657","channelNo":0,"type":7,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"J18155657","channelNo":0,"type":200,"enable":-1,"weekPlans":[{"weekDay":"0,1,2,3,4,5,6","timePlan":[]}]}]},"statusExtInfos":{"J18155657":{"upgradeAvailable":0}},"meta":{"code":200,"message":"操作成功","moreInfo":{}},"page":{"offset":0,"limit":100,"totalResults":0,"hasNext":false},"statusInfos":{"J18155657":{"diskNum":1,"diskState":"0---------------","globalStatus":1,"pirStatus":0,"isEncrypt":0,"upgradeAvailable":0,"upgradeProcess":0,"upgradeStatus":-1,"alarmSoundMode":0,"optionals":{"latestUnbandTime":"1658847519032","Remind_Way":"-1","BodyDetectTimeInterval":"-1","AlgorithmInfo":"[{\"SubType\":\"0\",\"channel\":1,\"Value\":\"3\"}]","Auto_night_vision":"-1","wanIp":"185.169.101.85","CustomVoice":"[]","Route_LinkageStatus":"0","hfullViewURL":"","daylightSavingTime":"0","Battery_WorkStatus":"{\"KeepAlive\":0,\"WorkTime\":0}","Alarm_DetectHumanCar":"{  \"type\": 0 }","tzCode":"146","CustomVoice_Volume":"{  \"volume\": 0 }","diskHealth":"-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1","httpPort":"0","OnlineStatus":"2","timeZone":"UTC+05:00","cmdPort":"0","ROI":"{  \"xCoord\": \"-1.00\",  \"yCoord\": \"-1.00\",  \"width\": \"-1.00\",  \"height\": \"-1.00\" }","upnpMappingMode":"0","diskCapacity":"32,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1","Temperature_Threshold":"-1","Alarm_Interval":"-1","domain":"J18155657","talkMode":"{  \"mode\": 1 }","NightVision_Model":"{  \"graphicType\": -1,  \"luminance\": -1 }","timeFormat":"1","ICR":"1","superState":"0","voiceIndex":"0","latestUnbindTime":"1658847519032"}}},"wifiInfos":{"J18155657":{"netName":"","netType":null,"address":null,"mask":null,"gateway":null,"signal":0,"ssid":null}},"switchStatusInfos":{"J18155657":[{"deviceSerial":"J18155657","channelNo":0,"type":2,"enable":true},{"deviceSerial":"J18155657","channelNo":0,"type":7,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":10,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":15,"enable":true},{"deviceSerial":"J18155657","channelNo":0,"type":22,"enable":true},{"deviceSerial":"J18155657","channelNo":0,"type":200,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":202,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":300,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":301,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":302,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":303,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":304,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":305,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":602,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":603,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":604,"enable":false},{"deviceSerial":"J18155657","channelNo":0,"type":700,"enable":false}]},"deviceInfos":[{"name":"Домофон","deviceSerial":"J18155657","fullSerial":"DS-KB8113-IME10120211203RRJ18155657","deviceType":"DS-KB8113-IME1","devicePicPrefix":"https://devpic.ezvizlife.com/device/image/DVR/","version":"V2.2.51 build 220507","supportExt":"{\"45\":\"1\",\"46\":\"1\",\"69\":\"1\",\"26\":\"4\",\"191\":\"1\",\"192\":\"1\",\"350\":\"1\",\"154\":\"0\",\"232\":\"0\",\"233\":\"0\",\"234\":1,\"333\":\"0\",\"30\":\"0\",\"52\":\"2\",\"31\":\"0\",\"97\":\"1\",\"10\":\"1\",\"77\":\"1\",\"78\":\"1\",\"13\":\"0\",\"59\":\"1\",\"241\":\"1\",\"165\":\"1\",\"1\":\"1\",\"2\":\"1\",\"145\":\"1\",\"288\":\"0\",\"3\":\"0\",\"400\":\"1\",\"5\":\"0\",\"401\":\"1\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"9\":\"0\",\"61\":\"1\",\"84\":\"1\"}","status":1,"userDeviceCreateTime":"2022-07-26 14:59:36","casIp":"cas.ezvizru.com","casPort":6500,"channelNumber":1,"hik":true,"deviceCategory":"COMMON","deviceSubCategory":"VIS","ezDeviceCapability":"{\"262\":\"1\",\"175\":\"1\",\"263\":\"0\",\"264\":\"1\",\"232\":\"0\",\"265\":\"1\",\"233\":\"0\",\"266\":\"0\",\"234\":1,\"267\":\"1\",\"289\":\"1\",\"30\":\"0\",\"31\":\"0\"}","customType":"DS-KB8113-IME1","offlineTime":"2022-09-19 17:14:37","offlineNotify":0,"accessPlatform":true,"deviceDomain":"J18155657","instructionBook":"http://devpic.ezvizlife.com/device/image/DS-KB8113-IME1/instruction.jpeg","deviceShareInfo":{"isShared":1,"permission":1,"inviterName":"jzmola"},"feature":null,"riskLevel":0,"offlineTimestamp":1663607677000}]}

**Comment by judge** [comment]
Hello,
It seems it's not a valid JSON file, could you please upload the response as a file?

**Comment by mbgdnv** [comment]
Done :)
[pagelist.json.txt](https://github.com/judge/homebridge-hikconnect/files/9616047/pagelist.json.txt)

**Comment by judge** [comment]
It seems that your device does not expose locks to this response. There should be a `lockNum` property here: `statusInfos.J18155657.optionals`.
I cannot see any lock related info in this response, so I'm not sure how can I proceed. :(
