### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by pergolafabio** [judge/homebridge-hikconnect#14]
Hi, you say you have not added camera (yet)
So you think it's possible? We also use the API in home assistant ,  but I checked the Hikconnect protocol, and couldn't find any API/command to retrieve the camera feed... 

I have only found options to indeed unlock, or call history or send ISAPi commands trough Hikconnect or abort/cancel/answer call... But no camera feed...

Have you found something then?

**Comment by judge** [comment]
No, sadly I don't have the skills to decrypt the camera feed. But I believe it should be possible because there is a live camera feed in the app.
If you have any tips or solutions, please share it. :)

**Comment by pergolafabio** [comment]
I think it's using the SDK....

Maybe it's possible to send the ISAPI command to retrieve the feed trough Hikconnect, I have found a way to send ISAPI commands

**Comment by pergolafabio** [comment]
Have a look here, I posted there an example how to send an ISAPi command...

https://github.com/tomasbedrich/home-assistant-hikconnect/issues/20#issuecomment-1021218537

**Comment by judge** [comment]
That is great news! Thanks for letting me know! I'll close this and I'll keep watching the other repo. :)
