### ISSUE TITLE
No locks showing on Hik outdoor Gen 1

### ISSUE THREAD

**Issue by kapps7** [judge/homebridge-hikconnect#16]
Hey mate,
I am not sure if this supposed to work on the gen 1.
The login is successful. The logs says initialising and there are no errors. However it picks up no accessories which there should be 2 if it works.
I have sent the output from the url as before to reddit via dm
Thanks!

**Comment by judge** [comment]
Hello,
I just checked the JSON response and it seems your devices does not return any locks (the script is looking for `lockNum`).  And I cannot see any similar info.
My guess is that this won't work with your devices. :(
