### ISSUE TITLE
Other types of devices

### ISSUE THREAD

**Issue by ur5zeb** [judge/homebridge-hikconnect#17]
Hello.  Is it possible to add other types of devices connected to the hikconnect cloud to your project?  I am very interested in the security panel and the sensors connected to it.  I have an AX Pro hub to which I connect leak detectors and door open sensors, as well as a relay, it would be great to throw it all into the Homekit.  There is also a calling panel to which I would like to see in the Home app.  Thanks for your work.

**Comment by judge** [comment]
Hi! Sadly I don't have any devices other than the doorbell. I'm using an unofficial API so there is no documentation available to implement these without having them/try them out.

**Comment by ur5zeb** [comment]
After the holidays, I’m on hand with AX PRO with leakage sensors and relays and I can provide you with access via hikconnect
