### ISSUE TITLE
All locks unresponsive 

### ISSUE THREAD

**Issue by jonathan337** [judge/homebridge-hikconnect#18]
Hi there!

Firstly, thanks for your work on this plug-in. I have been using this for months.

All of a sudden, around 2-3 days ago both my locks stopped responding. Nothing was changed on the rasberry pi. I have:

- Restarted the Rasberry Pi

- Restarted the HikVision Intercom

- Logged out of the HikConnect account via homebridge and logged back in. The locks are immediately exposed but still unresponsive

- Tried API URL : "https://www.hik-connectru.com" and “ https://ius.hik-connect.com/” instead of leaving it blank. I receive the below error with those URLs (no error if API URL is blank)

"Error: Login failed, wrong account or password

at HikConnectPlatform._loginToHikConnect (/var/lib/homebridge/node_modules/homebridge-hikconnect/src/index.js:49:13)

at processTicksAndRejections (node:internal/process/task_queues:95:5)

at HikConnectPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-hikconnect/src/index.js:30:7)"

_____________________________________________________________________________________

I'm extremely confused because this has been working flawlessly for almost two months and all these issues popped up out of the blue. Any help will be really appreciated.

I can provide any required logs, just let me know

I am also available on discord @jonathan_337

**Comment by judge** [comment]
Hi Jonathan! Do you see anything in the homebridge logs when you try to trigger the unlock in the Home app?

**Comment by jonathan337** [comment]
Unfortunately I don't see anything whenever I trigger the unlocks in the logs. For some reason, it started back working last night and just stopped again today and says "no response".

**Comment by jonathan337** [comment]
After some more testing, the locks work fine via the “Accessory” tab on Homebridge directly but they are unresponsive within HomeKit itself.

**Comment by judge** [comment]
It seems to me it's a HomeKit issue, not homebridge or the plugin. Are you able to unlock it when you are home? Did you maybe upgraded to the "new architecture" of HomeKit? I heard people have lot of issues since then.

**Comment by jonathan337** [comment]
I believe I have found the issue! I am not sure if Amazon did an upgrade to the Eeros or what changed - but it seems that the ports were being blocked. I have the Amazon Eero mesh system. I opened the port for Homebridge using the server's IP address and Homebridge's ports and so far, it has been working as it should all day. 

I believe port forwarding needed to be done! Thanks so much for your time.

**Comment by jonathan337** [comment]
Ok so update - the locks became non-responsive again but only within HomeKit, it works fine in HomeBridge. Any tips on fixing this?

**Comment by judge** [comment]
What about other devices connected through Hombridge? Do they get unresponsive or is it only the locks? It is very much likely that your network do this.

**Comment by jonathan337** [comment]
I believe I was able to identify the issue. I downgraded NodeJS from v19 to v18 and that seems to have solved the problem. I have no idea why that was causing it, but thankfully it's been stable for the last few days.

**Comment by judge** [comment]
I'm glad that it worked out for you! Is it still working? If yes, then I need to check the plugin with Node19. :)

**Comment by eumanecs** [comment]
Hi i dont see the Hikvision lock as accessory after installing plugin and providing credentials, doe the plugin support acces control device DS-K1T501SF?

**Comment by judge** [comment]
Hello, please follow this guide so I can see your device's reponses: [debugging guide](https://github.com/judge/homebridge-hikconnect/blob/main/DEBUGGING.md)
