### ISSUE TITLE
DS-KV6113-WPE1 Unresponding

### ISSUE THREAD

**Issue by bimon18** [judge/homebridge-hikconnect#19]
Hi Judge

Thanks for this work.

Sorry to disturb,
I'm trying to configure a DS-KV6113-WPE1 doorbell. My doorbell is Online on https://ieu.hik-connect.com. 
The lock/unlock is working well from the Hikconnect app.
![image](https://user-images.githubusercontent.com/126003397/220409008-ee5d2853-8d16-427c-abc3-5f9859918d88.png)

I install your plugin on homebridge (V1.6), and my doorbell is found with this serv https://ieu.hik-connect.com
![image](https://user-images.githubusercontent.com/126003397/220409373-8264f6ee-841e-48ec-b498-3512cff161a0.png)

But it is unresponding, from Home App, and from Homebridge Accessories.

I don't understand what i'm doing wrong. An idea ?
Thanks a lot

**Comment by bimon18** [comment]
I try to pick more information on:
https://api.hik-connect.com/v3/userdevices/v1/devices/pagelist?groupId=-1&limit=100&offset=0&filter=TIME_PLAN,CONNECTION,SWITCH,STATUS,STATUS_EXT,WIFI,NODISTURB,P2P,KMS,HIDDN

I find a locknum: 
lockNum | '{"1":1}'

**Comment by judge** [comment]
Hi!
Yes, that is the correct key so the plugin should work. Do you see anything in the Homebridge logs if you try to trigger your lock?

**Comment by bimon18** [comment]
Thanks for answer,

Nothing in the homebridge logs when i try to trigger. 

I found an alternative: i upgrade and put my internal station on Hikconnect (DS-KH6320-WTE1). A second lock was added in Homebridge, et this one is working !

The path is not optimized (iphone > Homebridge > Internal station > Doorbell > Gate), but it's working pretty well.

**Comment by judge** [comment]
Yes this plugin is primarily works with the internal component, but it's strange that the other component also exposes the lock correctly but the toggle is not working.
I'll close this for now, I'm happy that it's working for you! :)
