### ISSUE TITLE
Expose Hik lock as garage/gate

### ISSUE THREAD

**Issue by kapps7** [judge/homebridge-hikconnect#22]
Hey guys,
Wondering if anyone has been able to expose the locks so that it automatically shows up in CarPlay when approaching home like a normal garage/gate accessory.
If it doesnt I am not sure whether Siri allows control of an accessory verbally if you are using CarPlay at the time.
Thanks

**Comment by judge** [comment]
Hi! Currently the plugin registers locks as "LockMechanism" (https://developers.homebridge.io/#/service/LockMechanism) for Homekit. There is "GarageDoorOpener" (https://developers.homebridge.io/#/service/GarageDoorOpener) type as well, so probably if the plugin would register your locks as that type, they would show up.
I will try to come up with a solution to make this configurable. Do you have multiple locks? If so, do you want all of them show up as GarageDoorOpener?

**Comment by kapps7** [comment]
Hey mate.
In this case yes there is a drive in gate and a walk in gate so I would only want to expose the drive in gate as the garage accessory. That way I can get it show up in CarPlay.

Great if you can add it as a configuration option. I was thinking the other way would be to use the dummy garage switch  plugin and tie it to that. Doing it within your plugin would be more elegant ;)

**Comment by judge** [comment]
The problem with that I cannot control individual accessories. When the plugin starts, it will log in into HikConnect, gets all the devices and registers them as LockMechanism. I could create a config variable to be able to configure those as GarageDoorOpeners but then all of the locks will became that type.
Maybe the plugin you mentioned (https://github.com/rasod/homebridge-dummy-garage) + an automation could be a better solution.

**Comment by kapps7** [comment]
You're right because that would mess up CarPlay for all so. I'll go the dummy accessory. Thanks as always!
