### ISSUE TITLE
Two Homebridge with same Hik connect intercom locks

### ISSUE THREAD

**Issue by kapps7** [judge/homebridge-hikconnect#23]
Hey mate,
Just a question.

 If I setup to separate Homes in Apple with their own separate instances of homebridge, should I be able use the plugin to control the same hikconnect account and locks.
Hm just thinking as I type, maybe its better to share the lock with a second hik account for the second home.

**Comment by judge** [comment]
I think it should work, the plugin uses the credentials only for getting the lock device, it can be added multiple times to multiple homes.
