### ISSUE TITLE
Bitte um Hilfe!

### ISSUE THREAD

**Issue by Triwald** [judge/homebridge-hikconnect#24]
{
    "platform": "homebridge-hikconnect",
    "Account": "xxxxxxx@icloud.com",
    "Password": "xxxxxxxxxxxxx"
}

**Comment by judge** [comment]
Can you give me more context about the problem?

**Comment by Triwald** [comment]
HikConnectFEHLERError: HikConnect needs account and password specified in config

**Comment by judge** [comment]
This plugin is for Homebridge. Probably it can work with Hoobs as well but I have no idea how to set up account and password in Hoobs. :(
