### ISSUE TITLE
Error: Login failed

### ISSUE THREAD

**Issue by rbourg55** [judge/homebridge-hikconnect#3]
homebridge-hikconnect] Error: Error: Login failed, wrong account or password
    at HikConnectPlatform._loginToHikConnect (/usr/lib/node_modules/homebridge-hikconnect/src/index.js:46:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HikConnectPlatform.discoverDevices (/usr/lib/node_modules/homebridge-hikconnect/src/index.js:27:7)

    "account": "rxxxxx@yaxxxx.ru", ---- my email login hikconnect
    "password": "xxxxxx",  ----  my passw hikconnect
    "_bridge": {
        "username": "0E:88:CE:41:48:1A",
        "port": 51096
    },
    "platform": "HikConnect"

**Comment by judge** [comment]
Hello! Could you please check if you can login to hik-connect through the website? https://www.hik-connect.com
Sometimes if there are too many login attempts then you'll end up getting a Captcha.

**Comment by rbourg55** [comment]
Hi! I changed access to www.hik-connect.com/
but
[24.11.2021, 14:58:00] Homebridge v1.3.8 (HAP v0.9.7) (homebridge-hikconnect) is running on port 40074.
[DS-KV8113-WME1/1/0@@Model] characteristic value expected string and received undefined
[DS-KV8113-WME1/1/0@@Firmware Revision] characteristic value expected string and received undefined
[DS-KV8113-WME1/1/1@@Model] characteristic value expected string and received undefined
[DS-KV8113-WME1/1/1@@Firmware Revision] characteristic value expected string and received undefined

**Comment by judge** [comment]
That is really strange. So it seems now the script is able to log in but there is something wrong with the data. Could you please help me debugging the issue?
- log in to [hik-connect.com](https://www.hik-connect.com) in your web browser
- open this URL in a new tab: https://api.hik-connect.com/v3/userdevices/v1/devices/pagelist?groupId=-1&limit=100&offset=0&filter=TIME_PLAN,CONNECTION,SWITCH,STATUS,STATUS_EXT,WIFI,NODISTURB,P2P,KMS,HIDDN
- send me the the response by email (tamas.biro@gmail.com)

**Comment by hijacker123** [comment]
Is there a solution for the issue above available ?

I am receiving similar messages after start together with a Hikvision Doorbell DS-KV8113-WME.

```
[09/01/2022, 11:37:27] Homebridge v1.3.9 (HAP v0.9.8) (Homebridge ABB6) is running on port 51761
[09/01/2022, 11:37:29] [homebridge-hikconnect] Launched child bridge with PID 1702
[09/01/2022, 11:37:30] Registering platform 'homebridge-hikconnect.HikConnect'
[09/01/2022, 11:37:30] [homebridge-hikconnect] Loaded homebridge-hikconnect v1.1.0 child bridge successfully
[09/01/2022, 11:37:30] Loaded 1 cached accessories from cachedAccessories.0E32ADD5B6B3.
[09/01/2022, 11:37:30] Homebridge v1.3.9 (HAP v0.9.8) (homebridge-hikconnect) is running on port 57564.
[09/01/2022, 11:37:31] [homebridge-hikconnect] This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://git.io/JtMGR for more info.
[09/01/2022, 11:37:31] [homebridge-hikconnect] This plugin generated a warning from the characteristic 'Firmware Revision': characteristic value expected string and received undefined. See https://git.io/JtMGR for more info.
```

'Model string' = DS-KV8213-WME1
'Firmware version string' = V2.2.53 build 210907

**Comment by judge** [comment]
Could you help me debugging this issue with the steps I described in the previous comment? I got no response from @rbourg55 :(

**Comment by hijacker123** [comment]
> Could you help me debugging this issue with the steps I described in the previous comment? I got no response from @rbourg55 :(

Sure, how can I support you ?

**Comment by hijacker123** [comment]
> Could you help me debugging this issue with the steps I described in the previous comment? I got no response from @rbourg55 :(

I would like to remove my personal serial information and IP-Adresses...is this OK, still suitable ?

**Comment by hijacker123** [comment]
{"connectionInfos":{"E12345678":{"localIp":"XXX.XXX.XXX.XXX",“netIp“:“XXX.XXX.XXX.XXX“,"localRtspPort":0,"netRtspPort":0,"localCmdPort":9010,"netCmdPort":0,"localStreamPort":9020,"netHttpPort":0,"localHttpPort":0,"netStreamPort":0,"netType":3,"wanIp":null,"upnp":false}},"cameraInfos":[{"cameraId":"9ac07bbd952740ba9ef94d6d9204d5af","cameraName":"Door Station","channelNo":1,"cameraCover":"https://ieu.ezvizlife.com/assets/imgs/public/homeDevice.jpeg","deviceSerial":"E12345678","isShow":1,"videoLevel":2,"videoQualityInfos":[{"streamType":2,"videoLevel":0},{"streamType":1,"videoLevel":2}],"streamBizUrl":"biz=1","vtmInfo":{"domain":"vtmuceu.ezvizlife.com","externalIp":"128.1.42.99","internalIp":null,"port":10554,"forceStreamType":0,"isBackup":0},"deviceChannelInfo":{"channelDeviceSerial":null,"channelNo":1,"privacyStatus":0,"powerStatus":0,"globalStatus":0,"signalStatus":1},"cameraShareInfo":null}],"p2pInfos":{"E12345678":[{"ip":"34.250.216.38","port":6000},{"ip":"99.81.240.103","port":6000}]},"alarmNodisturbInfos":{"E12345678":{"alarmEnable":0,"callingEnable":0}},"kmsInfos":{"E12345678":{"secretKey":"af0e25c1a78378602c60b4b41b5d7b501b208241b00c0662f35465d45842a2af","version":"101"}},"timePlanInfos":{"E12345678":[{"deviceSerial":"E12345678","channelNo":0,"type":2,"enable":0,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"E12345678","channelNo":0,"type":4,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[{"startTime":"-1:65","endTime":"-1:65"}]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"E12345678","channelNo":0,"type":5,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"E12345678","channelNo":0,"type":7,"enable":-1,"weekPlans":[{"weekDay":"0","timePlan":[]},{"weekDay":"1","timePlan":[]},{"weekDay":"2","timePlan":[]},{"weekDay":"3","timePlan":[]},{"weekDay":"4","timePlan":[]},{"weekDay":"5","timePlan":[]},{"weekDay":"6","timePlan":[]}]},{"deviceSerial":"E12345678","channelNo":0,"type":200,"enable":-1,"weekPlans":[{"weekDay":"0,1,2,3,4,5,6","timePlan":[]}]}]},"statusExtInfos":{"E12345678":{"upgradeAvailable":0}},"meta":{"code":200,"message":"操作成功","moreInfo":{}},"page":{"offset":0,"limit":100,"totalResults":0,"hasNext":false},"statusInfos":{"E12345678":{"diskNum":1,"diskState":"0---------------","globalStatus":1,"pirStatus":0,"isEncrypt":0,"upgradeAvailable":0,"upgradeProcess":0,"upgradeStatus":-1,"alarmSoundMode":0,"optionals":{"latestUnbandTime":"1641574253987","Remind_Way":"-1","BodyDetectTimeInterval":"-1","AlgorithmInfo":"[{\"SubType\":\"0\",\"channel\":1,\"Value\":\"0\"}]","Auto_night_vision":"-1","wanIp":"217.224.164.83","CustomVoice":"[]","Route_LinkageStatus":"0","daylightSavingTime":"1","Battery_WorkStatus":"{\"KeepAlive\":0,\"WorkTime\":0}","Alarm_DetectHumanCar":"{  \"type\": 0 }","tzCode":"146","CustomVoice_Volume":"{  \"volume\": 0 }","diskHealth":"-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1","OnlineStatus":"2","timeZone":"UTC+01:00","ROI":"{  \"xCoord\": \"-1.00\",  \"yCoord\": \"-1.00\",  \"width\": \"-1.00\",  \"height\": \"-1.00\" }","diskCapacity":"32,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1","Temperature_Threshold":"-1","Alarm_Interval":"-1","lockNum":"{\"1\":1}","timeFormat":"2","talkMode":"{  \"mode\": 1 }","NightVision_Model":"{  \"graphicType\": -1,  \"luminance\": -1 }","ICR":"1","superState":"0","voiceIndex":"0","latestUnbindTime":"1641574253987"}}},"wifiInfos":{"E12345678":{"netName":"","netType":null,"address":null,"mask":null,"gateway":null,"signal":0,"ssid":null}},"switchStatusInfos":{"E12345678":[{"deviceSerial":"E12345678","channelNo":0,"type":2,"enable":true},{"deviceSerial":"E12345678","channelNo":0,"type":7,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":10,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":15,"enable":true},{"deviceSerial":"E12345678","channelNo":0,"type":22,"enable":true},{"deviceSerial":"E12345678","channelNo":0,"type":200,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":202,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":300,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":301,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":302,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":303,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":304,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":305,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":602,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":603,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":604,"enable":false},{"deviceSerial":"E12345678","channelNo":0,"type":700,"enable":false}]},"deviceInfos":[{"name":"Hikvision","deviceSerial":"E12345678","fullSerial":"DS-KV8213-WME10120200304RRE12345678","deviceType":"DS-KV8213-WME1","devicePicPrefix":"https://devpic.ezvizlife.com/device/image/DVR/","version":"V2.2.53 build 210907","supportExt":"{\"45\":\"1\",\"46\":\"1\",\"69\":\"1\",\"26\":\"4\",\"191\":\"1\",\"192\":\"1\",\"350\":\"1\",\"154\":\"0\",\"232\":\"0\",\"233\":\"0\",\"234\":1,\"333\":\"0\",\"30\":\"0\",\"52\":\"2\",\"31\":\"0\",\"97\":\"1\",\"10\":\"1\",\"77\":\"1\",\"78\":\"1\",\"13\":\"0\",\"59\":\"1\",\"241\":\"1\",\"165\":\"1\",\"1\":\"1\",\"2\":\"1\",\"145\":\"1\",\"288\":\"0\",\"3\":\"0\",\"400\":\"1\",\"5\":\"0\",\"401\":\"1\",\"6\":\"0\",\"7\":\"0\",\"8\":\"0\",\"9\":\"0\",\"61\":\"1\",\"84\":\"1\"}","status":1,"userDeviceCreateTime":"2022-01-07 17:42:02","casIp":"eucas.ezvizlife.com","casPort":6500,"channelNumber":1,"hik":true,"deviceCategory":"COMMON","deviceSubCategory":"VIS","ezDeviceCapability":"{\"262\":\"1\",\"175\":\"1\",\"263\":\"0\",\"264\":\"1\",\"232\":\"0\",\"265\":\"1\",\"233\":\"0\",\"266\":\"0\",\"234\":1,\"267\":\"1\",\"289\":\"1\",\"30\":\"0\",\"31\":\"0\"}","customType":"DS-KV8213-WME1","offlineTime":"2022-01-10 10:42:54","offlineNotify":0,"accessPlatform":true,"deviceDomain":"E12345678","instructionBook":"http://devpic.ezvizlife.com/device/image/DS-KV8213-WME1/instruction.jpeg","deviceShareInfo":null,"feature":null,"riskLevel":0,"offlineTimestamp":1641811374000}]}

**Comment by judge** [comment]
Thanks! I'll have a look soon!

**Comment by judge** [comment]
I just published a new version of the package, you should not see the warnings anymore. But it should have worked for you even with the warnings, so the question is, is the plugin working correctly for you?

**Comment by hijacker123** [comment]
> I just published a new version of the package, you should not see the warnings anymore. But it should have worked for you even with the warnings, so the question is, is the plugin working correctly for you?

I updated to v1.1.1
- The warnings are gone
- I get one one lock item "Hikvision/1/0". If I click on it, the doorbell relais is used including voice playback "door is open"

**Comment by judge** [comment]
That is strange. You only have 1 lock, right? I'll try to have a look soon with your JSON.

**Comment by judge** [comment]
I just checked the JSON and it seems to me you should have only 1 lock.
Could you try remove the devices and restart homebridge? If you go the Homebridge Settings (on the UI) there is a section called "Manage Cached Accessories" and then "Remove Single Cached Accessory".

**Comment by dbrownhill** [comment]
I'm seeing the following single log message, however nothing ever seems to happen. No accessories are added, no additional log messages, nothing. 

[2/11/2022, 9:24:32 AM] [HikConnect] Initializing HikConnect platform...


....I'll capture the JSON, and send it to you.

**Comment by judge** [comment]
Hi @dbrownhill ,

I checked the JSON and it is indeed no getting any locks, your JSON does not have any "lockNum" key which this plugin is searching for. Are you sure your devices have lock functionality?

**Comment by dbrownhill** [comment]
Yeah, still doesn’t work. Thanks though.

Best regards,
David
________________________________
