### ISSUE TITLE
Error: HikConnect needs account and password specified in config

### ISSUE THREAD

**Issue by alsolaim94** [judge/homebridge-hikconnect#8]
how to configure username and password
there is no spot for username and password, should i add it manually ?

Thank you in advance

5/2/2022, 5:54:03 PMHikconnect BridgeHikConnectERRORError: HikConnect needs account and password specified in config
5/2/2022, 5:54:03 PMHikconnect BridgeBridge is running on port 51846.
5/2/2022, 6:07:02 PMHikconnect Bridge stopping
5/2/2022, 6:07:02 PMHikconnect BridgeERRORdnsmasq: no process found
5/2/2022, 6:07:04 PMHikconnect BridgeERRORdnsmasq: no process found
5/2/2022, 6:30:16 PMbroadlinkrmprobridge stopping
5/2/2022, 6:30:22 PMBroadlink Rm Pro Bridge starting
5/2/2022, 6:38:22 PMeWeLink Bridge stopping
5/2/2022, 6:38:22 PMBroadlink Rm Pro Bridge stopping
5/2/2022, 6:38:32 PMWARNINGservice restart command received
5/2/2022, 6:38:43 PMhub is running on port 80
5/2/2022, 6:45:34 PMWARNINGdevice shutdown command received
5/2/2022, 6:54:27 PMhub is running on port 80
5/2/2022, 7:06:20 PMHikconnect Bridge starting
5/2/2022, 7:06:41 PMHikconnect BridgeLoaded plugin 'homebridge-hikconnect'
5/2/2022, 7:06:41 PMHikconnect BridgeLoading 1 platforms...
5/2/2022, 7:06:41 PMHikconnect BridgeHikConnectERRORError: HikConnect needs account and password specified in config
5/2/2022, 7:06:42 PMHikconnect BridgeBridge is running on port 51826.

**Comment by judge** [comment]
Hello,
If you are using homebridge UI then username and password should pop up when you install the plugin.
If not then you must edit the `config.json` file in your homebridge directory and extend the `platforms` section like this:
```
"platforms": [
  {
    "account": "<your account name>",
    "password": "<your password>",
    "platform": "HikConnect"
  }
]
```

**Comment by alsolaim94** [comment]
Thank you for your response 
> If you are using homebridge UI then username and password should pop up when you install the plugin.

Unfortunately I am using the web and app UI, but neither of them did pop up, asking for username and password.
I tried to factory reset my Hoobs, but did not work.

**Comment by judge** [comment]
Ah so you are using Hoobs. I'm not familiar with it but I think you should able to edit the configuration directly on the web UI: https://support.hoobs.org/docs/60e0d060646faaa152f10dda (check the advanced editor part)
